// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	domain "woman-center-be/internal/app/v1/models/domain"

	echo "github.com/labstack/echo/v4"

	exceptions "woman-center-be/utils/exceptions"

	mock "github.com/stretchr/testify/mock"

	multipart "mime/multipart"

	requests "woman-center-be/internal/web/requests/v1"
)

// CounselingPackageService is an autogenerated mock type for the CounselingPackageService type
type CounselingPackageService struct {
	mock.Mock
}

// CreatePackage provides a mock function with given fields: ctx, request, thumbnail
func (_m *CounselingPackageService) CreatePackage(ctx echo.Context, request requests.CounselingPackageRequest, thumbnail *multipart.FileHeader) (*domain.CounselingPackage, []exceptions.ValidationMessage, error) {
	ret := _m.Called(ctx, request, thumbnail)

	var r0 *domain.CounselingPackage
	var r1 []exceptions.ValidationMessage
	var r2 error
	if rf, ok := ret.Get(0).(func(echo.Context, requests.CounselingPackageRequest, *multipart.FileHeader) (*domain.CounselingPackage, []exceptions.ValidationMessage, error)); ok {
		return rf(ctx, request, thumbnail)
	}
	if rf, ok := ret.Get(0).(func(echo.Context, requests.CounselingPackageRequest, *multipart.FileHeader) *domain.CounselingPackage); ok {
		r0 = rf(ctx, request, thumbnail)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CounselingPackage)
		}
	}

	if rf, ok := ret.Get(1).(func(echo.Context, requests.CounselingPackageRequest, *multipart.FileHeader) []exceptions.ValidationMessage); ok {
		r1 = rf(ctx, request, thumbnail)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]exceptions.ValidationMessage)
		}
	}

	if rf, ok := ret.Get(2).(func(echo.Context, requests.CounselingPackageRequest, *multipart.FileHeader) error); ok {
		r2 = rf(ctx, request, thumbnail)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// DeletePackageById provides a mock function with given fields: ctx, id
func (_m *CounselingPackageService) DeletePackageById(ctx echo.Context, id int) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByTitle provides a mock function with given fields: ctx, title
func (_m *CounselingPackageService) FindByTitle(ctx echo.Context, title string) ([]domain.CounselingPackage, error) {
	ret := _m.Called(ctx, title)

	var r0 []domain.CounselingPackage
	var r1 error
	if rf, ok := ret.Get(0).(func(echo.Context, string) ([]domain.CounselingPackage, error)); ok {
		return rf(ctx, title)
	}
	if rf, ok := ret.Get(0).(func(echo.Context, string) []domain.CounselingPackage); ok {
		r0 = rf(ctx, title)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.CounselingPackage)
		}
	}

	if rf, ok := ret.Get(1).(func(echo.Context, string) error); ok {
		r1 = rf(ctx, title)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllPackage provides a mock function with given fields: ctx
func (_m *CounselingPackageService) GetAllPackage(ctx echo.Context) ([]domain.CounselingPackage, error) {
	ret := _m.Called(ctx)

	var r0 []domain.CounselingPackage
	var r1 error
	if rf, ok := ret.Get(0).(func(echo.Context) ([]domain.CounselingPackage, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(echo.Context) []domain.CounselingPackage); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.CounselingPackage)
		}
	}

	if rf, ok := ret.Get(1).(func(echo.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPackageById provides a mock function with given fields: ctx, id
func (_m *CounselingPackageService) GetPackageById(ctx echo.Context, id int) (*domain.CounselingPackage, error) {
	ret := _m.Called(ctx, id)

	var r0 *domain.CounselingPackage
	var r1 error
	if rf, ok := ret.Get(0).(func(echo.Context, int) (*domain.CounselingPackage, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(echo.Context, int) *domain.CounselingPackage); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CounselingPackage)
		}
	}

	if rf, ok := ret.Get(1).(func(echo.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePackageById provides a mock function with given fields: ctx, request, thumbnail
func (_m *CounselingPackageService) UpdatePackageById(ctx echo.Context, request requests.CounselingPackageRequest, thumbnail *multipart.FileHeader) (*domain.CounselingPackage, []exceptions.ValidationMessage, error) {
	ret := _m.Called(ctx, request, thumbnail)

	var r0 *domain.CounselingPackage
	var r1 []exceptions.ValidationMessage
	var r2 error
	if rf, ok := ret.Get(0).(func(echo.Context, requests.CounselingPackageRequest, *multipart.FileHeader) (*domain.CounselingPackage, []exceptions.ValidationMessage, error)); ok {
		return rf(ctx, request, thumbnail)
	}
	if rf, ok := ret.Get(0).(func(echo.Context, requests.CounselingPackageRequest, *multipart.FileHeader) *domain.CounselingPackage); ok {
		r0 = rf(ctx, request, thumbnail)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CounselingPackage)
		}
	}

	if rf, ok := ret.Get(1).(func(echo.Context, requests.CounselingPackageRequest, *multipart.FileHeader) []exceptions.ValidationMessage); ok {
		r1 = rf(ctx, request, thumbnail)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]exceptions.ValidationMessage)
		}
	}

	if rf, ok := ret.Get(2).(func(echo.Context, requests.CounselingPackageRequest, *multipart.FileHeader) error); ok {
		r2 = rf(ctx, request, thumbnail)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewCounselingPackageService creates a new instance of CounselingPackageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCounselingPackageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CounselingPackageService {
	mock := &CounselingPackageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
