// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	domain "woman-center-be/internal/app/v1/models/domain"

	mock "github.com/stretchr/testify/mock"
)

// CounselorFavoriteRepository is an autogenerated mock type for the CounselorFavoriteRepository type
type CounselorFavoriteRepository struct {
	mock.Mock
}

// AddCounselorFavorite provides a mock function with given fields: user, counselor
func (_m *CounselorFavoriteRepository) AddCounselorFavorite(user domain.Users, counselor *domain.Counselors) error {
	ret := _m.Called(user, counselor)

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.Users, *domain.Counselors) error); ok {
		r0 = rf(user, counselor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveCounselorFavorite provides a mock function with given fields: user, counselor
func (_m *CounselorFavoriteRepository) RemoveCounselorFavorite(user domain.Users, counselor *domain.Counselors) error {
	ret := _m.Called(user, counselor)

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.Users, *domain.Counselors) error); ok {
		r0 = rf(user, counselor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCounselorFavoriteRepository creates a new instance of CounselorFavoriteRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCounselorFavoriteRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CounselorFavoriteRepository {
	mock := &CounselorFavoriteRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
