// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	domain "woman-center-be/internal/app/v1/models/domain"

	echo "github.com/labstack/echo/v4"

	exceptions "woman-center-be/utils/exceptions"

	mock "github.com/stretchr/testify/mock"

	multipart "mime/multipart"

	requests "woman-center-be/internal/web/requests/v1"
)

// EventService is an autogenerated mock type for the EventService type
type EventService struct {
	mock.Mock
}

// CreateEvent provides a mock function with given fields: ctx, request, poster
func (_m *EventService) CreateEvent(ctx echo.Context, request requests.EventRequest, poster *multipart.FileHeader) (*domain.Event, []exceptions.ValidationMessage, error) {
	ret := _m.Called(ctx, request, poster)

	var r0 *domain.Event
	var r1 []exceptions.ValidationMessage
	var r2 error
	if rf, ok := ret.Get(0).(func(echo.Context, requests.EventRequest, *multipart.FileHeader) (*domain.Event, []exceptions.ValidationMessage, error)); ok {
		return rf(ctx, request, poster)
	}
	if rf, ok := ret.Get(0).(func(echo.Context, requests.EventRequest, *multipart.FileHeader) *domain.Event); ok {
		r0 = rf(ctx, request, poster)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(echo.Context, requests.EventRequest, *multipart.FileHeader) []exceptions.ValidationMessage); ok {
		r1 = rf(ctx, request, poster)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]exceptions.ValidationMessage)
		}
	}

	if rf, ok := ret.Get(2).(func(echo.Context, requests.EventRequest, *multipart.FileHeader) error); ok {
		r2 = rf(ctx, request, poster)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetAllEvent provides a mock function with given fields: ctx
func (_m *EventService) GetAllEvent(ctx echo.Context) ([]domain.Event, error) {
	ret := _m.Called(ctx)

	var r0 []domain.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(echo.Context) ([]domain.Event, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(echo.Context) []domain.Event); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(echo.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllEventMobile provides a mock function with given fields: ctx
func (_m *EventService) GetAllEventMobile(ctx echo.Context) ([]domain.Event, error) {
	ret := _m.Called(ctx)

	var r0 []domain.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(echo.Context) ([]domain.Event, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(echo.Context) []domain.Event); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(echo.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDetailEvent provides a mock function with given fields: ctx, id
func (_m *EventService) GetDetailEvent(ctx echo.Context, id int) (*domain.Event, error) {
	ret := _m.Called(ctx, id)

	var r0 *domain.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(echo.Context, int) (*domain.Event, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(echo.Context, int) *domain.Event); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(echo.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateEvent provides a mock function with given fields: ctx, request, poster
func (_m *EventService) UpdateEvent(ctx echo.Context, request requests.EventRequest, poster *multipart.FileHeader) ([]exceptions.ValidationMessage, error) {
	ret := _m.Called(ctx, request, poster)

	var r0 []exceptions.ValidationMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(echo.Context, requests.EventRequest, *multipart.FileHeader) ([]exceptions.ValidationMessage, error)); ok {
		return rf(ctx, request, poster)
	}
	if rf, ok := ret.Get(0).(func(echo.Context, requests.EventRequest, *multipart.FileHeader) []exceptions.ValidationMessage); ok {
		r0 = rf(ctx, request, poster)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]exceptions.ValidationMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(echo.Context, requests.EventRequest, *multipart.FileHeader) error); ok {
		r1 = rf(ctx, request, poster)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewEventService creates a new instance of EventService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventService(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventService {
	mock := &EventService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
