// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	domain "woman-center-be/internal/app/v1/models/domain"

	echo "github.com/labstack/echo/v4"

	exceptions "woman-center-be/utils/exceptions"

	mock "github.com/stretchr/testify/mock"

	requests "woman-center-be/internal/web/requests/v1"
)

// JobTypeService is an autogenerated mock type for the JobTypeService type
type JobTypeService struct {
	mock.Mock
}

// CreateJobType provides a mock function with given fields: ctx, request
func (_m *JobTypeService) CreateJobType(ctx echo.Context, request requests.JobTypeRequest) (*domain.Job_Type, []exceptions.ValidationMessage, error) {
	ret := _m.Called(ctx, request)

	var r0 *domain.Job_Type
	var r1 []exceptions.ValidationMessage
	var r2 error
	if rf, ok := ret.Get(0).(func(echo.Context, requests.JobTypeRequest) (*domain.Job_Type, []exceptions.ValidationMessage, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(echo.Context, requests.JobTypeRequest) *domain.Job_Type); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Job_Type)
		}
	}

	if rf, ok := ret.Get(1).(func(echo.Context, requests.JobTypeRequest) []exceptions.ValidationMessage); ok {
		r1 = rf(ctx, request)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]exceptions.ValidationMessage)
		}
	}

	if rf, ok := ret.Get(2).(func(echo.Context, requests.JobTypeRequest) error); ok {
		r2 = rf(ctx, request)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetJobType provides a mock function with given fields: ctx
func (_m *JobTypeService) GetJobType(ctx echo.Context) ([]domain.Job_Type, error) {
	ret := _m.Called(ctx)

	var r0 []domain.Job_Type
	var r1 error
	if rf, ok := ret.Get(0).(func(echo.Context) ([]domain.Job_Type, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(echo.Context) []domain.Job_Type); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Job_Type)
		}
	}

	if rf, ok := ret.Get(1).(func(echo.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewJobTypeService creates a new instance of JobTypeService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJobTypeService(t interface {
	mock.TestingT
	Cleanup(func())
}) *JobTypeService {
	mock := &JobTypeService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
