// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	requests "woman-center-be/internal/web/requests/v1"

	mock "github.com/stretchr/testify/mock"
)

// OtpService is an autogenerated mock type for the OtpService type
type OtpService struct {
	mock.Mock
}

// CreateAndSendingNewOtp provides a mock function with given fields: request
func (_m *OtpService) CreateAndSendingNewOtp(request requests.GenerateOTPRequest) error {
	ret := _m.Called(request)

	var r0 error
	if rf, ok := ret.Get(0).(func(requests.GenerateOTPRequest) error); ok {
		r0 = rf(request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VerifyOTP provides a mock function with given fields: request
func (_m *OtpService) VerifyOTP(request requests.VerifyOTPRequest) error {
	ret := _m.Called(request)

	var r0 error
	if rf, ok := ret.Get(0).(func(requests.VerifyOTPRequest) error); ok {
		r0 = rf(request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOtpService creates a new instance of OtpService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOtpService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OtpService {
	mock := &OtpService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
