// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	domain "woman-center-be/internal/app/v1/models/domain"

	mock "github.com/stretchr/testify/mock"
)

// PaymentMethodRepository is an autogenerated mock type for the PaymentMethodRepository type
type PaymentMethodRepository struct {
	mock.Mock
}

// GetAllBankMethod provides a mock function with given fields:
func (_m *PaymentMethodRepository) GetAllBankMethod() ([]domain.BankMethod, error) {
	ret := _m.Called()

	var r0 []domain.BankMethod
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.BankMethod, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.BankMethod); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.BankMethod)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPaymentMethodRepository creates a new instance of PaymentMethodRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentMethodRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentMethodRepository {
	mock := &PaymentMethodRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
