// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	resources "woman-center-be/internal/web/resources/v1"

	mock "github.com/stretchr/testify/mock"
)

// PaymentMethodService is an autogenerated mock type for the PaymentMethodService type
type PaymentMethodService struct {
	mock.Mock
}

// GetListBankMethod provides a mock function with given fields:
func (_m *PaymentMethodService) GetListBankMethod() ([]resources.BankMethodResource, error) {
	ret := _m.Called()

	var r0 []resources.BankMethodResource
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]resources.BankMethodResource, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []resources.BankMethodResource); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]resources.BankMethodResource)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPaymentMethodService creates a new instance of PaymentMethodService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentMethodService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentMethodService {
	mock := &PaymentMethodService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
