// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// RoleHandler is an autogenerated mock type for the RoleHandler type
type RoleHandler struct {
	mock.Mock
}

// CreateRoleHandler provides a mock function with given fields: _a0
func (_m *RoleHandler) CreateRoleHandler(_a0 echo.Context) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteRoleByIdHandler provides a mock function with given fields: _a0
func (_m *RoleHandler) DeleteRoleByIdHandler(_a0 echo.Context) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindRolesHandler provides a mock function with given fields: _a0
func (_m *RoleHandler) FindRolesHandler(_a0 echo.Context) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRoleHandler creates a new instance of RoleHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRoleHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *RoleHandler {
	mock := &RoleHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
