// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// SpecialistHandler is an autogenerated mock type for the SpecialistHandler type
type SpecialistHandler struct {
	mock.Mock
}

// CreateSpecialist provides a mock function with given fields: ctx
func (_m *SpecialistHandler) CreateSpecialist(ctx echo.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteSpecialistHandler provides a mock function with given fields: ctx
func (_m *SpecialistHandler) DeleteSpecialistHandler(ctx echo.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetListSpecialistHandler provides a mock function with given fields: ctx
func (_m *SpecialistHandler) GetListSpecialistHandler(ctx echo.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSpecialistHandler creates a new instance of SpecialistHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSpecialistHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *SpecialistHandler {
	mock := &SpecialistHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
