// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	domain "woman-center-be/internal/app/v1/models/domain"

	mock "github.com/stretchr/testify/mock"
)

// SpecialistRepository is an autogenerated mock type for the SpecialistRepository type
type SpecialistRepository struct {
	mock.Mock
}

// CreateSpecialist provides a mock function with given fields: tag
func (_m *SpecialistRepository) CreateSpecialist(tag *domain.Specialist) (*domain.Specialist, error) {
	ret := _m.Called(tag)

	var r0 *domain.Specialist
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.Specialist) (*domain.Specialist, error)); ok {
		return rf(tag)
	}
	if rf, ok := ret.Get(0).(func(*domain.Specialist) *domain.Specialist); ok {
		r0 = rf(tag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Specialist)
		}
	}

	if rf, ok := ret.Get(1).(func(*domain.Specialist) error); ok {
		r1 = rf(tag)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteSpecialistById provides a mock function with given fields: id
func (_m *SpecialistRepository) DeleteSpecialistById(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAllSpecialist provides a mock function with given fields:
func (_m *SpecialistRepository) FindAllSpecialist() ([]domain.Specialist, error) {
	ret := _m.Called()

	var r0 []domain.Specialist
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Specialist, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Specialist); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Specialist)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindById provides a mock function with given fields: id
func (_m *SpecialistRepository) FindById(id int) (*domain.Specialist, error) {
	ret := _m.Called(id)

	var r0 *domain.Specialist
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*domain.Specialist, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *domain.Specialist); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Specialist)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindSpecialistByName provides a mock function with given fields: name
func (_m *SpecialistRepository) FindSpecialistByName(name string) (*domain.Specialist, error) {
	ret := _m.Called(name)

	var r0 *domain.Specialist
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Specialist, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Specialist); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Specialist)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSpecialistRepository creates a new instance of SpecialistRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSpecialistRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SpecialistRepository {
	mock := &SpecialistRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
