// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	domain "woman-center-be/internal/app/v1/models/domain"

	mock "github.com/stretchr/testify/mock"
)

// TagRepository is an autogenerated mock type for the TagRepository type
type TagRepository struct {
	mock.Mock
}

// CreateTag provides a mock function with given fields: tag
func (_m *TagRepository) CreateTag(tag *domain.Tag_Article) (*domain.Tag_Article, error) {
	ret := _m.Called(tag)

	var r0 *domain.Tag_Article
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.Tag_Article) (*domain.Tag_Article, error)); ok {
		return rf(tag)
	}
	if rf, ok := ret.Get(0).(func(*domain.Tag_Article) *domain.Tag_Article); ok {
		r0 = rf(tag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Tag_Article)
		}
	}

	if rf, ok := ret.Get(1).(func(*domain.Tag_Article) error); ok {
		r1 = rf(tag)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTagById provides a mock function with given fields: tagID
func (_m *TagRepository) DeleteTagById(tagID int) error {
	ret := _m.Called(tagID)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(tagID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAllTags provides a mock function with given fields:
func (_m *TagRepository) FindAllTags() ([]domain.Tag_Article, error) {
	ret := _m.Called()

	var r0 []domain.Tag_Article
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Tag_Article, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Tag_Article); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Tag_Article)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindById provides a mock function with given fields: id
func (_m *TagRepository) FindById(id int) (*domain.Tag_Article, error) {
	ret := _m.Called(id)

	var r0 *domain.Tag_Article
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*domain.Tag_Article, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *domain.Tag_Article); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Tag_Article)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindTagByName provides a mock function with given fields: name
func (_m *TagRepository) FindTagByName(name string) (*domain.Tag_Article, error) {
	ret := _m.Called(name)

	var r0 *domain.Tag_Article
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Tag_Article, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Tag_Article); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Tag_Article)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTagRepository creates a new instance of TagRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTagRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TagRepository {
	mock := &TagRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
